### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [Foxpace/SensorBox#2]
It would be nice to have the app on F-Droid for FOSS users.

Izzy repo [requirements](https://gitlab.com/IzzyOnDroid/repo#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo)

But as @IzzySoft mentioned [here](https://gitlab.com/IzzyOnDroid/repo/-/issues/197) 8 offenders is too much.
```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Maps API (/com/google/android/gms/maps): NonFreeDep,NonFreeNet
* Play Services Places Placereport (/com/google/android/gms/places_placereport): NonFreeDep,NonFreeNet
* Android Wear APIs (/com/google/android/gms/wearable): NonFreeDep
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): Tracking

8 offenders.

```
Is it possible to have an APK on GitHub without these? or Can you narrow it down (for [izzyrepo](https://apt.izzysoft.de/fdroid/) release)?

Thankyou🙏

**Comment by Foxpace** [comment]
I removed the dependencies on firebase, which should eliminate 4 of them. However, if it is still not enough, I will be not able to help you futher. The reason is the app uses Google APIs to communicate with Wear Os, so the app for the Wear Os would be useless. Removal / changing of other dependencies would be costly / some features would be dropped. 

The apks can be found here: https://github.com/Foxpace/SensorBox/releases/tag/v4.2.2-nf

I did it quickly, so if there are some remnants, I will take another look on it.
