### ISSUE TITLE
can you help me in this problem 

### ISSUE THREAD

**Issue by Kawipat11** [Foxpace/SensorBox#3]
androidx.navigation.safeargs can only be used with an androidx project

**Comment by Foxpace** [comment]
Can you explain when the problem occures ? How to replicate it + some code, where is it happening ? Because just from that one line I am not able to give any precise suggestion. 

Have you tried something like this ? ->  https://stackoverflow.com/questions/55756571/cause-androidx-navigation-safeargs-can-only-be-used-with-an-androidx-project

**Comment by Kawipat11** [comment]
when I download this file and open it with android studio , it cant run this app and show alert like "A problem occurred configuring project ':app'. " (build.gradle(:app))
![image](https://user-images.githubusercontent.com/94850958/142990135-319ea44e-3ebe-4c86-b04e-68dcf15409c5.png)

**Comment by Kawipat11** [comment]
OK i can fixed it becase i dont have gradle.properties in this project
