### ISSUE TITLE
Firebase google-services.json issue

### ISSUE THREAD

**Issue by JackSaeure** [Foxpace/SensorBox#5]
Hey, I am planning to simplify the App to just record some wear Sensors and maybe also have a storage and graphical view on the recorded data.

But I struggle right away when downloading and running the code given.
after including the google-services.json that was missing, I get the Failure: 
```
"Execution failed for task ':wear:processDebugGoogleServices'.
> No matching client found for package name 'motionapps.sensorbox'"
```
when  running the code.

I am just starting to work myself into android programing, so..  maybe some hints how to make the app work from the sourcecode might be helpful.

Thanks, and Thanks for that grat piece of App!

**Comment by Foxpace** [comment]
Hello, 

I updated the README.md file with section how to build the app. I recommend to clone the project again with new gradle file in repository, if you are only beginning.

The error occurs, because you used wrong package name, double check that the package id from build gradle is identical to package name in firebase console in project settings.
